---
- hosts: all
  tasks:
    - name: Check if host vars file exists
      ansible.builtin.stat:
        path: "host_vars/{{ inventory_hostname }}.yml"
      register: host_vars_file
      tags: [always]

    - name: Load host-specific variables
      ansible.builtin.include_vars:
        file: "host_vars/{{ inventory_hostname }}.yml"
      tags: [always]
      when: host_vars_file.stat.exists

    - name: Include main vars
      ansible.builtin.include_vars: main.yml
      tags: [always]

    - name: Include monitoring vars
      ansible.builtin.include_vars: monitoring.yml
      tags: [always]

    - name: Include default vars
      ansible.builtin.include_vars: defaults/main.yml
      tags: [always]

    - name: Create directory structure for home staking role
      become_user: root
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      with_items:
        - "{{ host_config_mount }}"

    - name: Create Docker network
      docker_network:
        name: eth-staking-network-net
        state: present

    - name: Include task execution
      ansible.builtin.import_tasks: tasks/nethermind.yml
      tags: [execution]

    # - name: Import charon_leader role
    #   ansible.builtin.import_tasks: tasks/charon_leader.yml
    #   tags: [charon-leader]
    #   when: charon_enabled == 'true' and is_leader == 'true'

    - name: Import charon
      ansible.builtin.import_tasks: tasks/charon.yml
      tags: [charon]
      when: charon_enabled == 'true'

    - name: Import Consensus
      ansible.builtin.import_tasks: tasks/lighthouse.yml
      tags: [consensus]

    - name: Import Validator
      ansible.builtin.import_tasks: tasks/validator.yml
      when: validators is defined and validators | length > 0
      tags: [validator]

    - name: Install Cadvisor
      ansible.builtin.import_tasks: tasks/cadvisor.yml
      tags: cadvisor, always

    - name: Include task monitoring
      ansible.builtin.import_tasks: tasks/monitoring.yml
      tags: monitoring

    - name: Import mev-boost tasks
      ansible.builtin.import_tasks: tasks/mev-boost.yml
      when: mev_boost_enabled == 'true'
      tags: [mev]

  handlers:
    - name: reload cadvisor
      systemd:
        name: cadvisor.service
        state: restarted  
