metrics:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 15s
  configs:
    - name: default
      scrape_configs:
        - job_name: 'node-exporter'
          static_configs:
            - targets: ['node-exporter:9100']
        - job_name: 'cadvisor'
          static_configs:
            - targets: ['cadvisor:8080']
        - job_name: 'prometheus'
          metrics_path: /metrics/prometheus
          static_configs:
            - targets: ["{{ execution_docker_container_name }}:{{ execution_monitoring_port }}"]
