{
 "title": "Obol Charon Dashboard",
 "tags": [
  "obol",
  "charon"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Charon Node Uptime",
   "type": "graph",
   "description": "Shows the uptime of Charon nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Uptime" }
   ],
   "targets": [
    {
     "expr": "app_start_time_secs{job=\"charon-local\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "description": "Current slot being processed by Charon nodes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "core_scheduler_current_slot{job=\"charon-local\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Eth2 Network Latency",
   "type": "graph",
   "description": "Network latency for Eth2 communications",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "rate(app_eth2_latency_seconds_sum{job=\"charon-local\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}